version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

volumes:
  pg_data_dev:
