version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT:-3000}:3000
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - .env.dev
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    env_file:
      - .env.dev
    ports:
      - ${ADMINER_PORT:-8080}:8080
    depends_on:
      - postgres

volumes:
  pg_data_dev:
